task: generate .env files
The .env file is the only way docer-compose supports loading variables
that are globally available in the .docker-compose file. This file is
not committed because it's also used to inject secrets.

There are some variables that we need to keep track in the repository
because they contain all the different versions of components that need
to be used.

Sadly this results into more and more reliance on something like
Taskfile, but we're running into the limitations of docker-compose.

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -37,6 +37,19 @@ tasks:
         mkdir -p docker-images
         docker image save {{.image}} | pigz >docker-images/{{.image | replace "/" "-"}}.tar.gz
 
+  .generate-env:
+    cmds:
+      - |
+        if [ -f .env ] && ! grep -q '^# GENERATED' .env; then
+          echo "ERROR: Not overwriting non-generated .env file" >&2
+          exit 1
+        fi
+      - printf '# GENERATED\n\n' >.env
+      - cat build-args.env .env.* >>.env
+    deps: [ build-args ]
+    sources: [ .env.* ]
+    generates: [ .env ]
+
   build:
     description: "build all images"
     deps:
@@ -108,3 +121,8 @@ tasks:
   config:
     cmds:
       - docker-compose config
+
+  run:
+    cmds:
+      - docker-compose up -d
+    deps: [ .generate-env ]
